version: '3'

services: 
  database: 
    image: postgres:alpine
    container_name: postgres
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_DB: database
      POSTGRES_PASSWORD: password
    ports: 
      - 5432:5432